### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Barnag24** [Barnag24/UC#2]
Program doesn't start on Windows versions other than Windows 10.

**Comment by realvizu** [comment]
Does it throw an exception? If so, what exactly?

**Comment by Barnag24** [comment]
[ErrorTemp.zip](https://github.com/Barnag24/UC/files/477150/ErrorTemp.zip)
Windows 7 report files

**Comment by Barnag24** [comment]
Update: WMP has got nothing to do with the problem!

**Comment by realvizu** [comment]
The minidump says this is the exception:
A(z) „UndercoverDemo, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null” szerelvény NeutralResourcesLanguageAttribute attribútuma érvénytelen kulturáliskörnyezet-nevet határoz meg: „en-150”.

I've found it in the source in AssemblyInfo.cs:
[assembly: NeutralResourcesLanguage("en-150")]

I have no idea why is it here. Try to remove it.

**Comment by Barnag24** [comment]
[assembly: NeutralResourcesLanguage("en-150")] removed! It's working! :-D
